# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{monty}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["stonean"]
  s.date = %q{2010-05-03}
  s.description = %q{Rack based authoriztion system.}
  s.email = %q{andy@stonean.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "lib/monty.rb",
     "lib/monty/access.rb",
     "lib/monty/configuration.rb",
     "lib/monty/controller.rb",
     "lib/monty/permission.rb",
     "lib/monty/watch.rb",
     "monty.gemspec",
     "test/helper.rb",
     "test/monty/test_access.rb",
     "test/monty/test_configuration.rb",
     "test/monty/test_controller.rb",
     "test/monty/test_permission.rb",
     "test/monty/test_watch.rb",
     "test/rcov.opts",
     "test/test_monty.rb"
  ]
  s.homepage = %q{http://github.com/stonean/monty}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rack based authorization system}
  s.test_files = [
    "test/helper.rb",
     "test/monty/test_configuration.rb",
     "test/monty/test_controller.rb",
     "test/monty/test_access.rb",
     "test/monty/test_watch.rb",
     "test/monty/test_permission.rb",
     "test/test_monty.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
    else
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
    end
  else
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
  end
end

